### ISSUE TITLE
可以把 env 打入 jar 里面吗

### ISSUE THREAD

**Issue by caixinjiang** [xuanbo/fine-report#2]
请问, 打包时, 是否可以把 env/WEB-INF 也一起打包到 jar 里?
我尝试后, 启动报错, 找不到 web.xml.

11:11:49 main WARN [root] /private/var/folders/9l/mhswjt216gb2x5l3ndyj_9gc0000gn/T/tomcat-docbase.6847963713730182247.15020/WEB-INF/web.xml (No such file or directory)
 java.io.FileNotFoundException: /private/var/folders/9l/mhswjt216gb2x5l3ndyj_9gc0000gn/T/tomcat-docbase.6847963713730182247.15020/WEB-INF/web.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.fr.file.WebXmlConfigManager.analysisServlet(Unknown Source)

**Comment by xuanbo** [comment]
不可以，该方案是打包成spring boot jar，然后读取外部的env/WEB-INF配置（模板、数据源等）。
